export const brandCopy = {
  'headline.home.greetingTitle': 'Gunaydin, Lale',
  'headline.home.greetingSubtitle': 'Bugun ne yesek?',
  'headline.home.slogan': 'Komşunun mutfağından,\nkapına.',
  'helper.home.sloganSubline': 'Yakınındaki ev şeflerinden\nsıcacık yemekler 🍲',
  'helper.home.searchPlaceholder': 'Yemek ya da usta ara...',
  'helper.home.stockLimitTitle': 'Stok siniri',
  'helper.home.stockLimitMessage': 'Bu yemekte kalan kadar sepete ekleyebilirsin.',
  'helper.home.stockLinePrefix': 'Toplam:',
  'status.home.stockLineSuffix': 'kaldi',
  'helper.home.cartEmptyTitle': 'Sepetin su an bos.',
  'cta.home.cartCheckout': 'Sofrani hazirla',
  'cta.home.paymentRefresh': 'Durumu yenile',
  'cta.home.paymentNext': 'Sonraki odeme',
  'status.home.paymentTitle': 'Odeme durumu',
  'status.home.orderLabel': 'Siparis:',
  'status.home.orderStatusLabel': 'Durum:',
  'status.home.paymentDone': 'Odeme tamamlandi',
  'status.home.paymentWaiting': 'Odeme bekleniyor',
  'status.home.notificationsTitle': 'Bildirimler',
  'helper.home.notificationsEmpty': 'Yeni bildirimlerini burada goreceksin.',
  'status.home.messagesTitle': 'Mesajlar',
  'helper.home.messagesSubtitle': 'Ustalarla hizlica yazis',
  'helper.home.messageInputPlaceholder': 'Mesajini yaz...',
  'status.home.profileTitle': 'Profil',
  'cta.home.profileEdit': 'Profili duzenle',
  'cta.home.addresses': 'Adreslerim',
  'cta.home.settings': 'Ayarlar',
  'cta.home.logout': 'Cikis yap',
  'status.home.paymentWebTitle': 'Odeme ekrani',
  'cta.home.close': 'Kapat',
  'error.home.paymentModuleMissing': 'Uygulama ici odeme modulu bulunamadi.',
  'cta.home.openInBrowser': 'Tarayicida ac',
  'error.home.checkoutMissing': 'Odeme baglantisi su an bulunamiyor.',
  'cta.home.addToCart': 'Sepete ekle',
  'status.home.sellerKitchen': 'Usta Mutfagi',
  'status.home.sellerReviews': 'Yorumlar',
  'status.home.sellerReviewsLoading': 'Yorumlar yukleniyor...',
  'helper.home.sellerReviewsEmpty': 'Bu usta icin henuz yorum yok.',
  'helper.home.sellerCommentFallback': 'Yorum birakilmamis.',
  'status.home.sellerMeals': 'Ustanin yemekleri',
  'status.home.agentTitle': 'Mutfak asistani',
  'cta.home.retry': 'Tekrar dene',
  'status.home.connecting': 'Baglaniyor...',
  'helper.home.agentInputPlaceholder': 'Mesajini yaz...',
  'error.home.serverUnavailable502': 'Mutfak tarafinda kisa bir yogunluk var (502). Birazdan tekrar dene.',
  'error.home.serverUnavailable503': 'Sunucu su an mesgul (503). Birazdan tekrar dene.',
  'error.home.serverTimeout504': 'Sunucu gec cevap veriyor (504). Birazdan tekrar dene.',
  'error.home.serverGeneric': 'Sunucuda bir sorun var.',
  'error.home.requestFailed': 'Bir sorun oldu.',
  'error.home.unexpectedResponse': 'Sunucudan beklenmeyen bir cevap geldi.',
  'error.home.noMealsInResponse': 'Su an yemek listesi alinmiyor.',
  'error.home.retryLater': 'Su an ulasilamiyor. Lutfen tekrar dene.',
  'error.home.sessionExpired': 'Oturumun bitmis. Tekrar giris yap.',
  'helper.home.cartEmptyAlertTitle': 'Sepet bos',
  'helper.home.cartEmptyAlertMessage': 'Once sepete bir yemek ekleyelim.',
  'error.home.payableLotsMissing': 'Sepette odemeye uygun urun kalmadi.',

  'headline.login.title': 'Coziyoo',
  'headline.login.subtitle': 'Komsunun mutfagindan sicacik yemeklere hos geldin',
  'helper.login.emailLabel': 'E-posta',
  'helper.login.emailPlaceholder': 'ornek@mail.com',
  'helper.login.passwordLabel': 'Sifre',
  'helper.login.passwordPlaceholder': '••••••••',
  'cta.login.signIn': 'Giris yap',
  'cta.login.tryAgain': 'Tekrar dene',
  'error.login.invalidCredentials': 'E-posta ya da sifre dogru degil.',
  'error.login.accountLocked': 'Hesabin kilitli. E-postandaki linkle tekrar acabilirsin.',
  'error.login.tooManyAttempts': 'Cok hizli deneme yaptin. Biraz bekleyip tekrar dene.',
  'error.login.generic': 'Giris su an tamamlanamadi.',
  'error.login.emailRequired': 'E-posta yazman gerekiyor.',
  'error.login.passwordRequired': 'Sifre yazman gerekiyor.',
  'error.login.unexpectedResponse': 'Beklenmeyen bir cevap geldi.',
  'error.login.network': 'Baglanti sorunu var. Internetini kontrol edip tekrar dene.',

  'headline.address.title': 'Adreslerim',
  'cta.address.retry': 'Tekrar dene',
  'headline.address.emptyTitle': 'Henuz adres eklemedin',
  'helper.address.emptySubtitle': 'Siparis icin once bir teslimat adresi ekleyelim.',
  'cta.address.add': 'Adres ekle',
  'status.address.default': 'Varsayilan',
  'cta.address.setDefault': 'Varsayilan yap',
  'headline.address.edit': 'Adresi duzenle',
  'headline.address.new': 'Yeni adres',
  'helper.address.titleLabel': 'Adres basligi',
  'helper.address.titlePlaceholder': 'Ev, is, aile...',
  'helper.address.addressLabel': 'Acik adres',
  'helper.address.addressPlaceholder': 'Mahalle, sokak, bina, daire...',
  'helper.address.defaultToggle': 'Bunu varsayilan adres yap',
  'cta.address.update': 'Kaydet',
  'cta.address.save': 'Kaydet',
  'error.address.load': 'Adreslerini su an yukleyemedik.',
  'error.address.titleRequired': 'Adres basligi bos olamaz.',
  'error.address.addressTooShort': 'Adres en az 3 karakter olmali.',
  'error.address.save': 'Adresi su an kaydedemedik.',
  'error.address.delete': 'Adres su an silinemedi.',
  'error.address.default': 'Varsayilan adres su an degistirilemedi.',
  'helper.address.deleteTitle': 'Adresi sil',
  'helper.address.deleteMessage': 'Bu adresi silmek istedigine emin misin?',
  'cta.address.cancel': 'Vazgec',
  'cta.address.delete': 'Sil',

  'headline.profileEdit.title': 'Profili duzenle',
  'helper.profileEdit.displayNameLabel': 'Gorunen isim',
  'helper.profileEdit.displayNamePlaceholder': 'Adin nasil gorunsun?',
  'helper.profileEdit.fullNameLabel': 'Ad soyad',
  'helper.profileEdit.fullNamePlaceholder': 'Adini ve soyadini yaz',
  'helper.profileEdit.phoneLabel': 'Telefon',
  'helper.profileEdit.phonePlaceholder': '+90 5xx xxx xx xx',
  'helper.profileEdit.dobLabel': 'Dogum tarihi',
  'helper.profileEdit.dobPlaceholder': '1990-01-15',
  'helper.profileEdit.dobHint': 'Format: YYYY-AA-GG',
  'helper.profileEdit.countryLabel': 'Ulke kodu',
  'helper.profileEdit.countryPlaceholder': 'TR',
  'helper.profileEdit.languageLabel': 'Dil',
  'helper.profileEdit.languagePlaceholder': 'tr',
  'helper.profileEdit.emailLabel': 'E-posta',
  'status.profileEdit.buyer': 'Alici',
  'status.profileEdit.seller': 'Satici',
  'status.profileEdit.both': 'Alici & Satici',
  'helper.profileEdit.permissionTitle': 'Izin gerekiyor',
  'helper.profileEdit.permissionMessage': 'Galeriye erisim ver ki avatarini secebilelim.',
  'error.profileEdit.imageType': 'Sadece JPEG, PNG veya WebP sec.',
  'error.profileEdit.imageUpload': 'Resmi su an yukleyemedik.',
  'error.profileEdit.displayNameMin': 'Gorunen isim en az 3 karakter olmali.',
  'status.profileEdit.saved': 'Profilin guncellendi.',
  'cta.profileEdit.save': 'Kaydet',
  'helper.profileEdit.load': 'Profil su an yuklenemedi.',
  'error.profileEdit.save': 'Profil su an kaydedilemedi.',

  'headline.voice.disconnected': 'Baglanti kesildi',
  'helper.voice.disconnected': 'Oturum kapandi. Ne yapmak istersin?',
  'cta.voice.end': 'Bitir',
  'cta.voice.cancel': 'Kapat',
  'error.voice.setupTitle': 'Ses ayari tamamlanamadi',
  'status.voice.preparingTitle': 'Ses hazirlaniyor...',
  'helper.voice.preparingBody': 'Mikrofon ve hoparlor ayarlaniyor.',
  'error.voice.connectionTitle': 'Baglanti kurulamadi',
  'error.voice.mediaAccess': 'Mikrofon erisimi su an olmadi. Izinleri kontrol edip tekrar dene.',
  'cta.voice.back': 'Geri',
  'status.voice.connecting': 'Baglaniyor...',
  'status.voice.reconnecting': 'Tekrar baglaniyor...',
  'status.voice.disconnected': 'Baglanti kesildi',
  'status.voice.speaking': 'Usta konusuyor...',
  'status.voice.listening': 'Seni dinliyorum...',
  'helper.voice.subtitle': 'Ne yemek istedigini soyle',
  'status.voice.navAction': 'Sayfa aciliyor',
  'status.voice.addedAction': 'Sepete eklendi',
  'status.voice.orderSummaryAction': 'Siparis toplami hazir',

  'headline.settings.title': 'Ayarlar',
  'cta.settings.back': 'Geri',
  'headline.settings.connection': 'Baglanti',
  'helper.settings.apiBaseUrl': 'API adresi',
  'cta.settings.saveConnection': 'Baglantiyi kaydet',
  'cta.settings.saved': 'Kaydedildi',
  'headline.settings.aiServers': 'Yapay zeka sunuculari',
  'status.settings.agent': 'Asistan',
  'status.settings.language': 'Dil',
  'helper.settings.sttServer': 'STT sunucusu',
  'helper.settings.ttsServer': 'TTS sunucusu',
  'helper.settings.llmServer': 'LLM sunucusu',
  'cta.settings.saveServerSelection': 'Sunucu secimini kaydet',
  'helper.settings.noServers': 'Bu profilde sunucu bulunamadi. Admin panelinden STT/TTS/LLM ayarlarini yap.',
  'status.settings.disabled': 'pasif',
  'error.settings.load': 'Sunucu ayarlari yuklenemedi.',
  'error.settings.save': 'Kayit su an tamamlanamadi.',
} as const;

export type BrandCopyKey = keyof typeof brandCopy;

export function t(key: BrandCopyKey): string {
  return brandCopy[key];
}

export function stockLine(totalStock: number, remainingStock: number): string {
  return `${t('helper.home.stockLinePrefix')} ${totalStock}/${remainingStock} ${t('status.home.stockLineSuffix')}`;
}

export function requestErrorLine(status: number): string {
  return `${t('error.home.requestFailed')} (${status})`;
}
