export const brandCopy = {
  'headline.home.greetingTitle': 'Günaydın, Lale',
  'headline.home.greetingSubtitle': 'Bugün ne yesek?',
  'headline.home.slogan': 'Komşunun mutfağından, kapına.',
  'helper.home.sloganSubline': 'Yakınındaki ev şeflerinden sıcacık yemekler',
  'helper.home.searchPlaceholder': 'Yemek ya da usta ara...',
  'helper.home.stockLimitTitle': 'Stok sınırı',
  'helper.home.stockLimitMessage': 'Bu yemekte kalan kadar sepete ekleyebilirsin.',
  'helper.home.stockLinePrefix': 'Toplam:',
  'status.home.stockLineSuffix': 'kaldı',
  'helper.home.cartEmptyTitle': 'Sepetin şu an boş.',
  'cta.home.cartCheckout': 'Sofranı hazırla',
  'cta.home.paymentRefresh': 'Durumu yenile',
  'cta.home.paymentNext': 'Sonraki ödeme',
  'status.home.paymentTitle': 'Ödeme durumu',
  'status.home.orderLabel': 'Sipariş:',
  'status.home.orderStatusLabel': 'Durum:',
  'status.home.paymentDone': 'Ödeme tamamlandı',
  'status.home.paymentWaiting': 'Ödeme bekleniyor',
  'status.home.orderStatus.pending_seller_approval': 'Satıcı onayı bekleniyor',
  'status.home.orderStatus.seller_approved': 'Satıcı onayladı',
  'status.home.orderStatus.awaiting_payment': 'Ödeme bekleniyor',
  'status.home.orderStatus.preparing': 'Hazırlanıyor',
  'status.home.orderStatus.ready': 'Hazır',
  'status.home.orderStatus.in_delivery': 'Yolda',
  'status.home.orderStatus.delivered': 'Teslim edildi',
  'status.home.orderStatus.completed': 'Tamamlandı',
  'status.home.orderStatus.cancelled': 'İptal edildi',
  'status.home.orderStatus.rejected': 'Reddedildi',
  'status.home.paymentAttempt.initiated': 'Ödeme başlatıldı',
  'status.home.paymentAttempt.pending': 'Ödeme beklemede',
  'status.home.paymentAttempt.processing': 'Ödeme işleniyor',
  'status.home.paymentAttempt.succeeded': 'Ödeme başarılı',
  'status.home.paymentAttempt.failed': 'Ödeme başarısız',
  'status.home.paymentAttempt.canceled': 'Ödeme iptal edildi',
  'status.home.paymentAttempt.requires_action': 'Ödeme işlemi gerekiyor',
  'status.home.notificationsTitle': 'Bildirimler',
  'helper.home.notificationsEmpty': 'Yeni bildirimlerini burada göreceksin.',
  'status.home.messagesTitle': 'Mesajlar',
  'helper.home.messagesSubtitle': 'Ustalarla hızlıca yazış',
  'helper.home.messageInputPlaceholder': 'Mesajını yaz...',
  'status.home.profileTitle': 'Profil',
  'cta.home.profileEdit': 'Profili düzenle',
  'cta.home.myOrders': 'Siparişlerim',
  'helper.home.myOrdersHint': 'Geçmiş ve aktif siparişlerini gör',
  'cta.home.addresses': 'Adreslerim',
  'cta.home.deliveryAddressChange': 'Teslimat adresi değiştir',
  'helper.home.deliveryAddressHint': 'Siparişlerin bu adrese gider. Farklı yere geçtiysen buradan güncelle.',
  'cta.home.settings': 'Ayarlar',
  'cta.home.security': 'Güvenlik',
  'cta.home.logout': 'Çıkış yap',
  'headline.home.profileSellerTitle': 'Evinde yemek yapıp satmak ister misin?',
  'helper.home.profileSellerBody': "Coziyoo'da mutfağını gelire dönüştür.",
  'cta.home.becomeSeller': 'Satıcı Ol',
  'status.home.paymentWebTitle': 'Ödeme ekranı',
  'cta.home.close': 'Kapat',
  'error.home.paymentModuleMissing': 'Uygulama içi ödeme modülü bulunamadı.',
  'cta.home.openInBrowser': 'Tarayıcıda aç',
  'error.home.checkoutMissing': 'Ödeme bağlantısı şu an bulunamıyor.',
  'cta.home.addToCart': 'Sepete ekle',
  'status.home.sellerKitchen': 'Usta Mutfağı',
  'status.home.sellerReviews': 'Yorumlar',
  'status.home.sellerReviewsLoading': 'Yorumlar yükleniyor...',
  'helper.home.sellerReviewsEmpty': 'Bu usta için henüz yorum yok.',
  'helper.home.sellerCommentFallback': 'Yorum bırakılmamış.',
  'status.home.sellerMeals': 'Ustanın yemekleri',
  'status.home.agentTitle': 'Mutfak asistanı',
  'cta.home.retry': 'Tekrar dene',
  'status.home.connecting': 'Bağlanıyor...',
  'helper.home.agentInputPlaceholder': 'Mesajını yaz...',
  'error.home.serverUnavailable502': 'Mutfak tarafında kısa bir yoğunluk var (502). Birazdan tekrar dene.',
  'error.home.serverUnavailable503': 'Sunucu şu an meşgul (503). Birazdan tekrar dene.',
  'error.home.serverTimeout504': 'Sunucu geç cevap veriyor (504). Birazdan tekrar dene.',
  'error.home.serverGeneric': 'Sunucuda bir sorun var.',
  'error.home.requestFailed': 'Bir sorun oldu.',
  'error.home.unexpectedResponse': 'Sunucudan beklenmeyen bir cevap geldi.',
  'error.home.noMealsInResponse': 'Şu an yemek listesi alınmıyor.',
  'error.home.retryLater': 'Şu an ulaşılamıyor. Lütfen tekrar dene.',
  'error.home.sessionExpired': 'Oturumun bitmiş. Tekrar giriş yap.',
  'helper.home.cartEmptyAlertTitle': 'Sepet boş',
  'helper.home.cartEmptyAlertMessage': 'Önce sepete bir yemek ekleyelim.',
  'error.home.payableLotsMissing': 'Sepette ödemeye uygun ürün kalmadı.',
  'helper.home.checkoutDeliveryType': 'Teslimat tipi',
  'cta.home.delivery': 'Teslimat',
  'cta.home.pickup': 'Gel-al',
  'helper.home.checkoutAddress': 'Teslimat adresi',
  'cta.home.changeAddress': 'Adresi değiştir',
  'cta.home.manageAddresses': 'Adreslerimi yönet',
  'helper.home.noDefaultAddress': 'Varsayılan adresin yok. Devam etmek için adres seç.',
  'helper.home.addressRequiredCheckout': 'Teslimat için önce adres seçmelisin.',
  'headline.home.selectAddress': 'Teslimat adresi seç',
  'helper.home.selectAddressSubtitle': 'Bu sipariş için kayıtlı bir adres seç.',
  'helper.home.addressListEmpty': 'Kayıtlı adres bulunamadı.',

  'headline.login.title': 'Coziyoo',
  'headline.login.subtitle': 'Komşunun mutfağından sıcacık yemeklere hoş geldin',
  'helper.login.emailLabel': 'E-posta',
  'helper.login.emailPlaceholder': 'ornek@mail.com',
  'helper.login.passwordLabel': 'Şifre',
  'helper.login.passwordPlaceholder': '••••••••',
  'cta.login.signIn': 'Giriş yap',
  'cta.login.tryAgain': 'Tekrar dene',
  'error.login.invalidCredentials': 'E-posta ya da şifre doğru değil.',
  'error.login.accountLocked': 'Hesabın kilitli. E-postandaki linkle tekrar açabilirsin.',
  'error.login.tooManyAttempts': 'Çok hızlı deneme yaptın. Biraz bekleyip tekrar dene.',
  'error.login.generic': 'Giriş şu an tamamlanamadı.',
  'error.login.emailRequired': 'E-posta yazman gerekiyor.',
  'error.login.passwordRequired': 'Şifre yazman gerekiyor.',
  'error.login.unexpectedResponse': 'Beklenmeyen bir cevap geldi.',
  'error.login.network': 'Bağlantı sorunu var. İnternetini kontrol edip tekrar dene.',

  'headline.address.title': 'Adreslerim',
  'cta.address.retry': 'Tekrar dene',
  'headline.address.emptyTitle': 'Henüz adres eklemedin',
  'helper.address.emptySubtitle': 'Sipariş için önce bir teslimat adresi ekleyelim.',
  'cta.address.add': 'Adres ekle',
  'status.address.default': 'Varsayılan',
  'cta.address.setDefault': 'Varsayılan yap',
  'headline.address.edit': 'Adresi düzenle',
  'headline.address.new': 'Yeni adres',
  'helper.address.titleLabel': 'Adres başlığı',
  'helper.address.titlePlaceholder': 'Ev, iş, aile...',
  'helper.address.addressLabel': 'Açık adres',
  'helper.address.addressPlaceholder': 'Mahalle, sokak, bina, daire...',
  'helper.address.defaultToggle': 'Bunu varsayılan adres yap',
  'cta.address.update': 'Kaydet',
  'cta.address.save': 'Kaydet',
  'error.address.load': 'Adreslerini şu an yükleyemedik.',
  'error.address.titleRequired': 'Adres başlığı boş olamaz.',
  'error.address.addressTooShort': 'Adres en az 3 karakter olmalı.',
  'error.address.save': 'Adresi şu an kaydedemedik.',
  'error.address.delete': 'Adres şu an silinemedi.',
  'error.address.default': 'Varsayılan adres şu an değiştirilemedi.',
  'helper.address.deleteTitle': 'Adresi sil',
  'helper.address.deleteMessage': 'Bu adresi silmek istediğine emin misin?',
  'cta.address.cancel': 'Vazgeç',
  'cta.address.delete': 'Sil',

  'headline.profileEdit.title': 'Profili düzenle',
  'helper.profileEdit.displayNameLabel': 'Görünen isim',
  'helper.profileEdit.displayNamePlaceholder': 'Adın nasıl görünsün?',
  'helper.profileEdit.displayNameHint': 'Uygulamada görünen adın',
  'helper.profileEdit.fullNameLabel': 'Ad soyad',
  'helper.profileEdit.fullNamePlaceholder': 'Adını ve soyadını yaz',
  'helper.profileEdit.fullNameHint': 'Gerçek adın ve soyadın',
  'helper.profileEdit.phoneLabel': 'Telefon',
  'helper.profileEdit.phonePlaceholder': '+90 5xx xxx xx xx',
  'helper.profileEdit.phoneHint': 'İletişim numaran',
  'helper.profileEdit.dobLabel': 'Doğum tarihi',
  'helper.profileEdit.dobPlaceholder': '1990-01-15',
  'helper.profileEdit.dobHint': 'Format: YYYY-AA-GG',
  'helper.profileEdit.countryLabel': 'TC Kimlik No',
  'helper.profileEdit.countryPlaceholder': '11 haneli kimlik no',
  'helper.profileEdit.emailLabel': 'E-posta',
  'helper.profileEdit.emailHint': 'Kayıtlı e-posta adresin',
  'status.profileEdit.verified': 'Doğrulandı',
  'cta.profileEdit.edit': 'Düzenle',
  'headline.profileEdit.accountSection': 'Hesap bilgileri',
  'headline.profileEdit.securitySection': 'Şifre değiştir',
  'helper.profileEdit.forgotPasswordHint': 'Şifremi unuttum, e-postama doğrulama kodu gönder',
  'cta.profileEdit.sendResetCode': 'Kodu gönder',
  'helper.profileEdit.codeLabel': 'Doğrulama kodu',
  'helper.profileEdit.codePlaceholder': '6 haneli kod',
  'helper.profileEdit.newPasswordLabel': 'Yeni şifre',
  'helper.profileEdit.newPasswordPlaceholder': 'En az 8 karakter',
  'helper.profileEdit.newPasswordAgainLabel': 'Yeni şifre (tekrar)',
  'helper.profileEdit.newPasswordAgainPlaceholder': 'Yeni şifreyi tekrar yaz',
  'cta.profileEdit.changePassword': 'Şifreyi güncelle',
  'error.profileEdit.passwordRequired': 'Kod ve şifre alanlarını doldurman gerekiyor.',
  'error.profileEdit.passwordMin': 'Yeni şifre en az 8 karakter olmalı.',
  'error.profileEdit.passwordMismatch': 'Yeni şifreler aynı değil.',
  'error.profileEdit.codeRequired': 'Doğrulama kodunu girmen gerekiyor.',
  'status.profileEdit.resetCodeSent': 'Kod gönderildi. E-postanı kontrol et.',
  'status.profileEdit.buyer': 'Alıcı',
  'status.profileEdit.seller': 'Satıcı',
  'status.profileEdit.both': 'Alıcı & Satıcı',
  'helper.profileEdit.permissionTitle': 'İzin gerekiyor',
  'helper.profileEdit.permissionMessage': 'Galeriye erişim ver ki avatarını seçebilelim.',
  'error.profileEdit.imageType': 'Sadece JPEG, PNG veya WebP seç.',
  'error.profileEdit.imageUpload': 'Resmi şu an yükleyemedik.',
  'error.profileEdit.displayNameMin': 'Görünen isim en az 3 karakter olmalı.',
  'status.profileEdit.saved': 'Profilin güncellendi.',
  'cta.profileEdit.save': 'Kaydet',
  'helper.profileEdit.load': 'Profil şu an yüklenemedi.',
  'error.profileEdit.save': 'Profil şu an kaydedilemedi.',
  'helper.profileEdit.noDefaultAddress': 'Varsayılan adres yok',
  'helper.profileEdit.defaultAddressLoading': 'Varsayılan adres yükleniyor...',

  'headline.voice.disconnected': 'Bağlantı kesildi',
  'helper.voice.disconnected': 'Oturum kapandı. Ne yapmak istersin?',
  'cta.voice.end': 'Bitir',
  'cta.voice.cancel': 'Kapat',
  'error.voice.setupTitle': 'Ses ayarı tamamlanamadı',
  'status.voice.preparingTitle': 'Ses hazırlanıyor...',
  'helper.voice.preparingBody': 'Mikrofon ve hoparlör ayarlanıyor.',
  'error.voice.connectionTitle': 'Bağlantı kurulamadı',
  'error.voice.mediaAccess': 'Mikrofon erişimi şu an olmadı. İzinleri kontrol edip tekrar dene.',
  'cta.voice.back': 'Geri',
  'status.voice.connecting': 'Bağlanıyor...',
  'status.voice.reconnecting': 'Tekrar bağlanıyor...',
  'status.voice.disconnected': 'Bağlantı kesildi',
  'status.voice.speaking': 'Usta konuşuyor...',
  'status.voice.listening': 'Seni dinliyorum...',
  'helper.voice.subtitle': 'Ne yemek istediğini söyle',
  'status.voice.navAction': 'Sayfa açılıyor',
  'status.voice.addedAction': 'Sepete eklendi',
  'status.voice.orderSummaryAction': 'Sipariş toplamı hazır',

  'headline.settings.title': 'Güvenlik',
  'cta.settings.back': 'Geri',
  'cta.settings.done': 'Tamam',
  'helper.settings.securitySubtitle': 'Hesabının güvenliğini yönet',
  'helper.settings.passwordLastChanged': 'Son değiştirme: 2 ay önce',
  'helper.settings.twoFactorSubtitle': 'Ek güvenlik katmanı',
  'helper.settings.twoFactorComingSoon': 'Bu özellik yakında açılacak.',
  'headline.settings.whyImportant': 'Neden Önemli?',
  'helper.settings.whyImportantBody': 'Şifreni düzenli değiştirmen ve iki aşamalı doğrulamayı açman hesabını korur.',
  'headline.settings.connection': 'Bağlantı',
  'helper.settings.apiBaseUrl': 'API adresi',
  'cta.settings.saveConnection': 'Bağlantıyı kaydet',
  'cta.settings.saved': 'Kaydedildi',
  'headline.settings.aiServers': 'Yapay zeka sunucuları',
  'status.settings.agent': 'Asistan',
  'status.settings.language': 'Dil',
  'helper.settings.sttServer': 'STT sunucusu',
  'helper.settings.ttsServer': 'TTS sunucusu',
  'helper.settings.llmServer': 'LLM sunucusu',
  'cta.settings.saveServerSelection': 'Sunucu secimini kaydet',
  'helper.settings.noServers': 'Bu profilde sunucu bulunamadı. Admin panelinden STT/TTS/LLM ayarlarını yap.',
  'status.settings.disabled': 'pasif',
  'status.security.passwordTitle': 'Şifre',
  'status.security.emailVerification': 'E-posta Doğrulama',
  'status.security.phoneVerification': 'Telefon Doğrulama',
  'status.security.twoFactorTitle': 'İki Aşamalı Doğrulama',
  'status.security.off': 'Kapalı',
  'status.security.phoneFallback': '+90 5xx xxx xx xx',
  'cta.security.changePassword': 'Şifre Değiştir',
  'cta.security.changeEmail': 'E-posta Değiştir',
  'cta.security.changePhone': 'Telefon Numarasını Değiştir',
  'cta.security.enable': 'Etkinleştir',
  'error.settings.load': 'Sunucu ayarları yüklenemedi.',
  'error.settings.save': 'Kayıt şu an tamamlanamadı.',
} as const;

export type BrandCopyKey = keyof typeof brandCopy;

const HOME_SUBTITLE_GENERIC_VARIANTS = [
  'Bugün ne yemek istersin?',
  'Canın ne çekiyorsa ona bakalım.',
  'Sana güzel bir şey öneririm.',
  'En çok satanlara bir göz atalım mı?',
  'Birlikte hızlıca bir şey seçelim mi?',
  'Bence bugün kendini güzel bir yemekle şımart.',
] as const;

const HOME_SUBTITLE_DAYPART_VARIANTS = {
  morning: [
    'Kahvaltıda ne istersin?',
    'Kahvaltını yaptın mı, acıktın mı?',
    'Sana mis gibi bir kahvaltı öneririm.',
    'Bugün hafif mi gidelim, doyurucu mu?',
  ],
  noon: [
    'Ne yemek istersin, beraber seçelim.',
    'Sana şimdi iyi gidecek bir şey öneririm.',
    'Öğlen acıktın mı, ne yiyelim?',
    'Bir tık ev yemeği moduna geçelim mi?',
  ],
  evening: [
    'Canın ne istiyorsa ona gidelim.',
    'Sana sıcacık bir şey öneririm.',
    'Akşam yemeği için ne düşünüyorsun?',
    'Bugün menüyü beraber toparlayalım mı?',
  ],
} as const;

export function t(key: BrandCopyKey): string {
  return brandCopy[key];
}

export function randomHomeGreetingSubtitle(date = new Date()): string {
  const hour = date.getHours();
  const dayPart =
    hour < 11
      ? 'morning'
      : hour < 17
        ? 'noon'
        : 'evening';

  const pool = [
    ...HOME_SUBTITLE_DAYPART_VARIANTS[dayPart],
    ...HOME_SUBTITLE_GENERIC_VARIANTS,
  ];

  return pool[Math.floor(Math.random() * pool.length)] ?? 'Bugün ne yesek?';
}

export function stockLine(totalStock: number, remainingStock: number): string {
  return `${t('helper.home.stockLinePrefix')} ${totalStock}/${remainingStock} ${t('status.home.stockLineSuffix')}`;
}

export function requestErrorLine(status: number): string {
  return `${t('error.home.requestFailed')} (${status})`;
}
